name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Outdated Builds
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Enable Rust Caching
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Audit
        run: cargo audit

      - name: Format Check
        run: cargo fmt -- --check

      - name: Cargo Clippy
        run: cargo clippy

      - name: Check Bench
        run: cargo bench --no-run

      - name: Check Ignored Tests
        run: cargo test --release --no-run -- --ignored

      - name: Test
        run: cargo test --release
